### ISSUE TITLE
Can't compile on CentOs 7.9

### ISSUE THREAD

**Issue by www-asics-ws** [lanyu7/dpc_linux#11]
Can't compile.

CentOS Linux release 7.9.2009 (Core)
Linux cpu11 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

g++ -Wl,-O1 -Wl,-z,relro -o DrevoPowerConsole main.o mainwindow.o qkeyboardctrl.o qkeyboardctrl_init.o customkeywidget.o custombutton.o customknobwidget.o keysetwidget.o radilightwidget.o devicecomm.o devicedb.o qtkeyboardkey.o moc_mainwindow.o moc_qkeyboardctrl.o moc_customkeywidget.o moc_custombutton.o moc_customknobwidget.o moc_keysetwidget.o moc_radilightwidget.o qrc_keyboard_layout.o    -L/usr/lib64 -Lusr/local/lib -lusb-1.0 -L./lib/ -lhidkeyboard -lQtSql -lQtGui -lQtCore -lpthread
./lib//libhidkeyboard.a(keyboarddata.o):(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
collect2: error: ld returned 1 exit status
make: *** [DrevoPowerConsole] Error 1

Any idea how to solve this ?

**Comment by www-asics-ws** [comment]
I was using the wrong qt. When running qmake, make sure you pick the correct one. For me it was:
/usr/lib/qt5/bin/qmake -makefile DrevoPowerConsole.pro
